### PR TITLE
add possibility of custom tex template 

### PR DESCRIPTION
**Pull request by PhilippImhof**
added new command line parameter `--tex_template` in order to allow a custom tex template

if not specified, default file is used. if specified but not available (file not found or file not readable), an error message is shown and the default is used.

This pull request would at least close issues https://github.com/3b1b/manim/pull/745 and https://github.com/3b1b/manim/issues/525 .

### CODE REVIEW

**Comment by PhilippImhof** [comment]
I have completely rewritten the code for managing the TeX template:

- Full backwards compatibility: if you do nothing, everything will work as before, the old default template will be used for LaTeX or XeLaTeX
- New command line option `--tex_template` allows for a custom tex file
- New class `TeXTemplate`starting with the current default values for maximum backwards compatibility.
- New class has methods to append or prepend custom packages and/or custom preamble commands.
- Added method `register_tex_template` allows to register a new or modified template

**Example**

```
class ExampleScene(Scene):
    def construct(self):
        tpl=TeXTemplate()
        tpl.append_package(["esvect",["f"]])
        register_tex_template(tpl)

        text=TextMobject(r"$\vv{vb}$")
        self.play(Write(text))
```

As you may have guessed, the syntax for packages is
- `append_package("package")` if you do not have any options
- `append_package(["package",["option1","option2=value2"]])` if you do have options to give

**Comment by Ammar34** [comment]
Got an error after making all the changes. Can you please help?
AttributeError: 'NoneType' object has no attribute 'get_text_for_tex_mode'

**Comment by PhilippImhof** [comment]
@Ammar34 I am happy to help, but I need more information: 

* What is your input?
* What is the **exact** error message? (preferably with the stack trace)

With the information you provide, there is absolutely no way for me to help.

**Comment by Ammar34** [comment]
@PhilippImhof yeah okay. Prior to changes suggested by your commit, I was getting no error. After the changes I am getting the following in the terminal:

PS E:\VisualStudioCode\manim> python -m manim graphingFile.py firstPlot -pm
Traceback (most recent call last):
  File "C:\Users\Khan-\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Khan-\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code     
    exec(code, run_globals)
  File "E:\VisualStudioCode\manim\manim.py", line 5, in <module>
    manimlib.main()
  File "E:\VisualStudioCode\manim\manimlib\__init__.py", line 11, in main
    config = manimlib.config.get_configuration(args)
  File "E:\VisualStudioCode\manim\manimlib\config.py", line 189, in get_configuration
    module = get_module(args.file)
  File "E:\VisualStudioCode\manim\manimlib\config.py", line 184, in get_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "graphingFile.py", line 1, in <module>
    from manimlib.imports import *
  File "E:\VisualStudioCode\manim\manimlib\imports.py", line 104, in <module>
    from manimlib.new_packages.new_classes import *
  File "E:\VisualStudioCode\manim\manimlib\new_packages\new_classes.py", line 82, in <module>
    class CheckFormulaByTXT(Scene):
  File "E:\VisualStudioCode\manim\manimlib\new_packages\new_classes.py", line 86, in CheckFormulaByTXT 
    "text": TexMobject(""),
  File "E:\VisualStudioCode\manim\manimlib\mobject\svg\tex_mobject.py", line 149, in __init__
    SingleStringTexMobject.__init__(
  File "E:\VisualStudioCode\manim\manimlib\mobject\svg\tex_mobject.py", line 43, in __init__
    file_name = tex_to_svg_file(
  File "E:\VisualStudioCode\manim\manimlib\utils\tex_file_writing.py", line 20, in tex_to_svg_file     
    tex_file = generate_tex_file(expression, tex_template, source_type)
  File "E:\VisualStudioCode\manim\manimlib\utils\tex_file_writing.py", line 36, in generate_tex_file   
    output = tex_template.get_text_for_tex_mode(expression)
AttributeError: 'NoneType' object has no attribute 'get_text_for_tex_mode'
PS E:\VisualStudioCode\manim>

**Comment by PhilippImhof** [comment]
What is `manim\manimlib\new_packages\new_classes.py` ? This does not exist in my code and I cannot find it in the main repository either.

**Comment by Ammar34** [comment]
@PhilippImhof Ah! That was the problem. It was an old classes file that I forgot to delete. Thanks. Now its working.
P.S Can you please explain how can I change the tex template to any custom template I want? A code example would be deary of you!

**Comment by PhilippImhof** [comment]
@Ammar34 I'm glad I could help.

In order to use a custom tex template, you basically have two possibilities

### Template file
You prepare a template file (complete LaTeX file starting with `\documentclass[preview]{standalone}` plus your preamble containing all desired packages followed by 
```
\begin{document}
   YourTextHere
\end{document}
```
The template can then be used by invoking manim with the new '--tex-template <file>' command line option.

### Template object
You create a new `TeXTemplate` object within your scene's constructor. The template will be initialized with the default packages for best compatibility, check `manimlib/tex_template.tex` for reference. The object then offers you to add custom packages directly in your code. After everything is done, you have to "register" your template object:

```
class ExampleScene(Scene):
    def construct(self):
        tpl=TeXTemplate()
        tpl.append_package("siunitx") # add package without options
        tpl.append_package(["esvect",["f"]]) # add package with one option
        tpl.append_package(["spalign",["systelims=||","delims=()"]]) # add package with multiple options and keyval syntax
        tpl.append_to_preamble(r"\newcommand{\tr}{\operatorname{tr}}") # add definition to preamble
        register_tex_template(tpl)

        text=TextMobject(r"$\vv{vb}$")
        self.play(Write(text))
```
There is also a method `clear_preamble` if you do not want to have all the default packages in your template. I do not think there is a need for this, as those packages normally should not make any problems, but I decided to include it nevertheless, for maximum flexibility.

**Pull request closed without merging**
