### PR TITLE
handle_play_like_call decorator to use functools.wraps

### PR DESCRIPTION
**Pull request by parmentelat**
this is a remake of https://github.com/3b1b/manim/pull/1204 on the current master

this way, decorated methods - typically Scene.play - have a decent docstring
so first-time users can use help()

### CODE REVIEW

**Review by TonyCrane — APPROVED** [review]
But there are two more wrappers. You can also improve them by the way:
https://github.com/3b1b/manim/blob/8f52c7bda8e298d15d3958ba76bc56648d4a9e19/manimlib/mobject/mobject.py#L1289-L1295 https://github.com/3b1b/manim/blob/8f52c7bda8e298d15d3958ba76bc56648d4a9e19/manimlib/mobject/types/vectorized_mobject.py#L809-L816

**Comment by parmentelat** [comment]
that's right, I had proposed to take care of that in my initial PR, but had forgotten about all this in the meanwhile :)

I am in no position to test all  this though at this time, the code I had written in summer last year looks broken with the current version (where is the `Paragraph` class now ?), and I could not spot any automated tests (did I miss them ?)

in any case, here you go ...

**Comment by TonyCrane** [comment]
This version has been developed since last year, so `Paragraph` and `Code` are not included in it. For testing, 3b1b/manim probably has never had a well-formed and complete test. But ManimCommunity/manim has.

**Comment by parmentelat** [comment]
are you suggesting I use the community version instead if I need `Paragraph` and `Code` ? otherwise where shoud I grab them ?
more generally, I was not aware of these 2 flavours, where should I read about that do get up to speed ?

many thanks for the feedback !

**Comment by TonyCrane** [comment]
It may be that `Paragraph` and `Code` were mistakenly missed when merging shaders branch into master, but you can still use the old version that contains them in the `cairo-backend` branch now. 
For ManimCommunity/manim, there is a big difference between the two versions at present, and there is a brief description of the difference in #1243. These two versions all have advantages, which one you use depends on you.
If you want to talk more, maybe you can start a discussion instead of this pr.

**Pull request merged**
