### PR TITLE
Change fill color and stroke color independently

### PR DESCRIPTION
**Pull request by jerpint**
Thanks for contributing to manim!

**Please ensure that your pull request works with the latest version of manim.**
You should also include:

1. The motivation for making this change (or link the relevant issues)

Motivation: using the `set_color` function would change both the stroke and fill color, which is not always convenient (one may wish to change one but not the other).

2. How you tested the new behavior (e.g. a minimal working example, before/after
screenshots, gifs, commands, etc.) This is rather informal at the moment, but
the goal is to show us how you know the pull request works as intended.

In this case, if an argument is not provided, the color is simply not updated.

### CODE REVIEW

**Comment by eulertour** [comment]
In order to be consistent with the old behavior, you should have the stroke color default to the fill color if none is specified.

**Comment by jerpint** [comment]
I find the old behaviour misleading, i.e. changing the color forces the change to the fill color and stroke color by default. By having the `stroke_color` default to `None`, the stroke color is simply not updated unless you explicitly state so.

**Comment by eulertour** [comment]
In that case you should create new functions to set the fill color and stroke color separately and we can see if set_color can be deprecated.

**Comment by jerpint** [comment]
Would it be too misleading to name it `set_colors` instead of `set_color`?
```
    def set_colors(self, fill_color=None, stroke_color=None, family=True):
        self.set_fill(fill_color, family=family)
        self.set_stroke(stroke_color, family=family)
        return self
```

**Comment by 3b1b** [comment]
If you want to actively think about which aspect of the color you're changing, the best ways are:

mob.set_stroke(color=_____)

or

mob.set_fill(color=______)

These also make very clear in the code what the intention is.  Does that not serve what you're going for?

The thinking behind set_color changing both is that most objects are drawn with fill and no stroke (like TexMobjects) or stroke and no fill (like lines, rectangles, etc.), and if you just want to change its color without thinking about that you can just call set_color.

In fact, it would almost certainly cause frustrations if set_color just changed the fill and not the stroke.  Think of an early user who creates a line, then tries to call "line.change_color(RED)" with no effect.

**Comment by jerpint** [comment]
ah ok that makes more sense. I'm still new to manim and have been using it primarily with Square objects in the context of building grids, so for me strokes and fills are both necessary. I hadn't thought of the use case you mention since I haven't come across it yet, but I can see how it would happen a lot. 

Closing this issue :+1:

**Pull request closed without merging**
