### PR TITLE
Featured a blog post about installing the Manim

### PR DESCRIPTION
**Pull request by mitkonikov**
Maybe it will help grow the support and the community around this project.

### CODE REVIEW

**Comment by anthonynorthrup314** [comment]
Without trying to sound rude, there are some issues with your tutorial(s) for installing Manim.
The first post is pretty good, though the grammar needs a bit of work.
The second post has a lot of errors:
- You should be copying the `__init__.py` file anywhere, it's in the Manim folder so python will treat the directory as a package, you can read more about that [here](https://pythontips.com/2013/07/28/what-is-__init__-py/).
- The `example_scenes.py` file should also not be copied out of the Manim folder, when you specify it in the command line, it can be a local path, or an absolute path. Since you are running python from the Scripts folder, and not the Manim folder, it will check there for local paths. If you instead executed the following, you wouldn't have any issues:
    ```
    C:\WINDOWS\system32> cd ../../Python27/Manim
    C:\Python27\Manim> "C:/Python27/Scripts/python" extract_scene.py -w example_scenes.py SquareToCircle
    ```
    Alternatively, you could add it to the path as you mentioned in the first post, and just reference it as `python`.
- If you are going to modify the `MOVIE_DIR` variable to a fixed path, you can get rid of the `os.path.join()` surrounding it, and instead just have: `MOVIE_DIR = "<your output folder path>"`.
- The error you are seeing at the end: `The system cannot find the path specified` is because it plays a chord when it finishes rendering a scene, you can find this method at the top of the `helpers.py` file: `play_chord(*nums)`. It tries to call a program `play`, which isn't installed on Windows, I installed [SoX](http://sox.sourceforge.net/) on my Arch Linux installation (package [here](https://www.archlinux.org/packages/extra/x86_64/sox/)) when getting Manim setup.

**Comment by mitkonikov** [comment]
Check it out, now.. I corrected them just like you said... Thank you!

**Comment by anthonynorthrup314** [comment]
Better, though I recommend verifying installing SoX is a fix for Windows. From the looks of the Manim code, this is developed for Linux, some of the changes I recommended were also from me developing on Linux, which might not be applicable on Windows.
The command line snippets you have on the second blog are still referring to the Manim folder, rather than being called from *inside* the Manim folder. You did change them on the first post, but not on the second.
Thanks for the shout out for the updates by the way.

**Comment by anthonynorthrup314** [comment]
Another thing that might be worth making a post about, is how to get the text rendering working. When I first tried this project on my Linux installation, there were a lot of issues with dvisvgm and latex (what Manim uses to convert text to SVG for rendering). On the README for Manim it mentions having ffmpeg and latex installed before using, you made a post about ffmpeg, so latex seems like the next step.

**Comment by mitkonikov** [comment]
I corrected what you have said. I made a new screenshot with the new path structure and MOVIE_DIR... I think that it's complete now. And, you are right, the next step is latex. I installed latex, but it seems that there is a issue when creating a .svg file... It says that it's missing some .svg file in the /files/Tex.. So, can help me get through this issue...? Also, is there an option that allows me to make you a contributor on my blog, so you can easily correct stuff...?

**Comment by anthonynorthrup314** [comment]
I think you can follow the steps [here](https://support.google.com/blogger/answer/42673?hl=en) for allowing me to edit your blog. You can use my email, which should be visible to you on my profile.

I think one last edit though, at the top of the second post is a snippet:
```
python "C:/Python27/Manim/extract_scene.py" -p example_scenes.py SquareToCircle
```
You should change it to the following to match the screenshots below and the snippet at the end of the first post:
```
python extract_scene.py -p example_scenes.py SquareToCircle
```

**Comment by anthonynorthrup314** [comment]
As for the LaTeX issue, if you have a file `<NUMBERS>.tex` in the /files/Tex directory, try calling the conversion calls (found at the bottom of `mobject/tex_mobject.py`) manually (but with logging) from the command line. For example:
```
> cd /files/Tex/
> copy "<NUMBERS>.tex" test.tex
> latex -halt-on-error test.tex
> dvisvgm test.dvi -n -o test.svg
```
If there aren't any errors at each step, it should convert properly when running the python file, if there are any errors, let me know.

**Comment by mitkonikov** [comment]
Done, done and done!
Just it pops an error on the last command: 

`C:\Python27\Manim\files\Tex>dvisvgm test.dvi -n -o test.svg
pre-processing DVI file (format version 2)
processing page 1
  computing extents based on data set by preview package (version 11.91)
  width=0pt, height=7.319pt, depth=7.31985e-06pt
  page is empty
  graphic size: 0pt x 7.31901pt (0mm x 2.57234mm)
  ERROR: table value 175872 out of range`

The latex command was a success... But this one, seems the width is the problem somehow...

**Comment by anthonynorthrup314** [comment]
Alright, I've seen [that issue](https://github.com/mgieseki/dvisvgm/issues/79) before, I think it can be fixed by installing the [latest dvisvgm](https://github.com/mgieseki/dvisvgm/releases/tag/2.2.3)

**Comment by mitkonikov** [comment]
Boom! THANK YOU VERY MUCH!
It worked.. We can write about it in the next blog post.. I tried it with the scene 'WriteStuff', it is complete success. Thank you again!

**Comment by anthonynorthrup314** [comment]
No problem, if you ever want me to look over another post, just send me an email. I don't think this pull request should be used for much more. Even if this request doesn't get merged, writing a blog for various aspects of Manim would be useful to anyone who's interested, so keep at it.

**Comment by mitkonikov** [comment]
You are absolutely right. I will send you an email if I write couple of new posts about the Manim and we shouldn't use this pull request for further conversations. Thank you again for helping me out.

**Comment by zhangwn** [comment]
I'm trying to install it, but I'm having trouble. Whenever I run `pip install -r -requirements.txt` I get `RecursionError: maximum recursion depth exceeded'.

**Comment by rajdakin** [comment]
@zhangwn I think the right command is `pip install -r requirements.txt` (you wrote `-requirements.txt`). It should fix, otherwise follow his tutorial if you are a Windows user. And you should have created a new issue, not posted this comment in this pull request.

**Pull request closed without merging**
