### PR TITLE
Fixed self.add_sound() for W10 and Community Examples

### PR DESCRIPTION
**Pull request by zavden**
Linux and Mac: `subprocess.call(["rm", sound_file_path])`
Windows: `os.remove(sound_file_path)`

But, this could works in the three OS?

### CODE REVIEW

**Comment by xy-23** [comment]
I think it can works in the three os because it is a python-built-in method.
But I only have windows platform to test.

**Comment by zavden** [comment]
Ready @xy-23

**Comment by eulertour** [comment]
Switching to `os.remove()` is a good idea, but community examples shouldn't go in this repo.

**Comment by zavden** [comment]
Ok, let me sended the new one

**Pull request closed without merging**
