### PR TITLE
Manim depends on Python 2.7 and is not yet compatible with Python 3.

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by hemangjoshi37a** [comment]
so you should raise a issue not do pull request....

**Comment by cclauss** [comment]
This PR documents the current state of affairs in the README which will save aggression for readers.  I see nothing wrong with this approach.

**Comment by clintonb** [comment]
@hemangjoshi37a discouraging pull requests is not a great way to foster contributions. Looking at his history, @cclauss has done a lot to try to make the codebase compatible with Python 3 (See #96 and #97), and hasn't received much support/feedback. I empathize with that frustration.

I also sympathize with the burden of maintaining an open source package, which is why I must ask: @3b1b @Sridhar3b1b, do you need help maintaining this library? A few folks seem to benefit from it, and want to help maintain it; however, their pull requests have gone unacknowledged for many weeks. I am one of the maintainers of https://github.com/jsocol/django-waffle. I'd be happy to either advise you on building a community, or actively help maintain the project (e.g. review issues and PRs, setup CI, update documentation, etc.). The beauty of open source is that you don't have to do all of the work alone.

At the very least, if you are not open to contributions, you might consider updating the README to reflect this fact, and avoid future frustration.

**Comment by 3b1b** [comment]
Sure, I'd be open to what help/advice in maintenance you might be willing to provide.

I do regret not being more attentive to some of the pull requests put forth.  The switch to Python 3 as a particular example is honestly just something I've bee putting off, with the intent of just sitting down at some point and making sure do to it as cleanly as possible in one swoop and thinking critically about what unexpected side effects there might be.

For context, part of the reason I can seem so inattentive here is that maintenance of the library is (unfortunately) somewhat low on the current list of priorities.  Most of our time goes towards thinking about the math and writing itself, followed by a focus on creating specific visuals, and the state of the library falls behind those concerns.  And that's just on the creative half, my time is also often pulled towards certain more business-oriented concerns.

Which is all to say that your help is quite welcomed :), but attending to it is something I have up until now not really thought about working into my habits.

As a start, do you have advice, or perhaps a checklist, for switching things to python 3?

**Comment by cclauss** [comment]
Checklist at https://docs.python.org/3/howto/pyporting.html

**Pull request merged**
