### PR TITLE
progress fixes

### PR DESCRIPTION
**Pull request by casperdcl**
- removed unused `progressbar` dependency
- updated `tqdm` (was an ancient 2 year old! https://tqdm.github.io/releases/#v4240-2018-07-26)
- correct `ascii` fallback auto-detection, related https://github.com/tqdm/tqdm/issues/454

### CODE REVIEW

**Comment by huguesdevimeux** [comment]
Hi, could you move this PR on ManimCommunity repository ? https://github.com/ManimCommunity/manim
This change seems to be useful.

**Comment by casperdcl** [comment]
done (https://github.com/ManimCommunity/manim/pull/192)

**Comment by casperdcl** [comment]
any reason this was closed without merging?

**Comment by TonyCrane** [comment]
Sorry for that. Maybe this is outdated. If you want, you can reopen a new PR.

**Pull request closed without merging**
