### PR TITLE
CodeMobject to display code with color highlighted

### PR DESCRIPTION
**Pull request by NavpreetDevpuri**
you can use it as follow.
format code from https://codebeautify.org/cpp-formatter-beautifier with select intent = 2 means tab spacing = 2
save html file from https://tohtml.com/cpp/ select style = 'black'
```python
from manimlib.mobject.code_mobject import *
code = CodeMobject("Helloword.html",
                           coordinates=[-5,3],
                           run_time=3,
                           scale_factor=0.3,
                           line_spacing=0.2,
                           tab_spacing=0.6,
                           font='Monospac821 BT')
        #self.draw_code_all_lines_at_a_time(code)
        code.scale(1)
        self.play(Write(code),run_time=1)

    def draw_code_all_lines_at_a_time(self, code):
        self.play(*[Write(code[i]) for i in range(code.__len__())],run_time=code.run_time)
```
coordinate point is LEFT+UP corner. 
'code' is a 2d array of characters.
for example to access first 5 characters from line 2 use `code[2][0:5]`
```python
code[2][0:5].set_color(RED)
```

Output will be looks like 
code

* It solves the following problems
1) display code with color highlighted
2) manage to print single LaTeX character '{' or '}' because of using Text() instead TextMobject() from https://github.com/3b1b/manim/issues/941#issuecomment-621615699

### CODE REVIEW

**Comment by tshrpl** [comment]
wow! this will be really usefull if the pull request is accepted ...

**Comment by safinsingh** [comment]
It would be nice if you could change the font specifically for this Mobject to make it look more like code!

**Comment by NavpreetDevpuri** [comment]
> It would be nice if you could change the font specifically for this Mobject to make it look more like code!

Updated !

**Comment by NavpreetDevpuri** [comment]
https://github.com/3b1b/manim/issues/1017

it have that issue.

**Comment by NavpreetDevpuri** [comment]
Reopening it with new branch

**Pull request closed without merging**
