### PR TITLE
Add animation documentation and asset folder

### PR DESCRIPTION
**Pull request by Kolloom**
Animation documentation is not yet complete.
Asset folder contains renders from code snipples.

Update constants.rst to include a ref tag
Update index to include the animation doc

There is no official policy for video media. I created a asset folder and throw some examples in. 
While linking youtube video do work, I think that is quite inconvenient for individual examples.

### CODE REVIEW

**Comment by eulertour** [comment]
I merged this without viewing it locally, but I suspect you didn't mean for the video to appear as download links. I think you can do this with a path for the `src` attribute.
```
.. raw:: html

    <iframe width="560" height="315" src="https://www.youtube.com/embed/8tvYDIGLJJA?ecver=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
```

**Comment by Kolloom** [comment]
Ah yes thanks. I will probably do that via substitution. 
PS: The youtube video linked in readthedocs is down.

**Comment by eulertour** [comment]
I know, I'll have to link it from the assets dir one day, or you could do it if I'm too slow.

**Comment by Kolloom** [comment]
``  <iframe width="560" height="315" src="./../../../source/assets/AnimationFadeIn.mp4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`` 

can't get the path to resolve unfortunately. 

``Firefox can’t find the file at /home/thompson/manim/docs/build/html/assets/AnimationFadeIn.mp4.``

**Pull request merged**
