### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Sir-Teo**

### CODE REVIEW

**Comment by 3b1b** [comment]
Which part requires this?

**Comment by Sir-Teo** [comment]
In ```manim.py```.

After I install all the prerequisites in ```requirement.txt```,  and ran 
```
python3 -m manim example_scenes.py SquareToCircle -pl
```
the terminal complained missing package ```watchdog```. 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/manim/manim.py", line 9, in <module>
    from watchdog.observers import Observer
ModuleNotFoundError: No module named 'watchdog'
```
Then I ran ```pip install watchdog```, the problem was solved.  S

**Comment by eulertour** [comment]
I used that library as part of an experimental feature I was working on a while ago, but I never finished it and don't think I will. That said, it looks like you're using a version of manim other than the latest.

**Comment by Sir-Teo** [comment]
Oh i see. I am using docker and cloning from ```https://github.com/eulertour/manim.git``` according to the instructions in readme. 
probably this information isn't up to date.

**Comment by eulertour** [comment]
Sorry, I just updated this in 03e832af45e16bd0f6d7d8d45739384c22044f3f.

**Comment by Sir-Teo** [comment]
Great! Then I will close this pull request.

**Pull request closed without merging**
