### PR TITLE
Add better discontinuity functionality.

### PR DESCRIPTION
**Pull request by ddxtanx**
1. The motivation for making this change (or link the relevant issues)
 I made this change because I wanted to work with some algebraic curves that have multiple infinite discontinuities and, with the current version of manim, animating them lead to very ugly artifacts appearing on the curve. This fundamentally boils down to the `discontinuities` array appearing in the ParametricFunction class that we needed to "be smarter about." While this isn't a perfect solution (as there are still 'double-tangent' artifacts present in all the examples (without and with the new discontinuities function), this is a little bit smarter.
2. How you tested the new behavior (e.g. a minimal working example, before/after
screenshots, gifs, commands, etc.) This is rather informal at the moment, but
the goal is to show us how you know the pull request works as intended.
 The image below demonstrates the issue I was attempting to solve.
ParametricFunctionScene_With_Old_Discont
 With the new `get_discontinuities` function I coded, the image becomes
ParametricFunctionScene_With_New_Discont
 And, to test both infinite discontinuities and break discontinuities, I just drew a hyperbola with a step function at the tail end, which looked like:
ParametricFunctionScene_Inf_And_Break_Discont
So the issue is solved, and everything should _still_ work.

### CODE REVIEW

**Comment by ddxtanx** [comment]
With the new break discontinuity detection, the tangent lines in the curve now disappear, while still making sure the break in the step function is gone as well.

image
image

**Comment by ddxtanx** [comment]
Latest commit addresses #694 by extending discontinuity detection to GraphScene graphs.

**Comment by ddxtanx** [comment]
And on appropriate choice of tol_point (I set it equal to 15, since this example's y axis only goes to 1.5 and x axis to 10) the graph becomes:
image
which is free of vertical line artifacts.

**Comment by ddxtanx** [comment]
> These discontinuity artifacts also seem to be an issue with complex functions as well.
> 
> Relevant issue: #498

From what I can see in the ComplexFunctionScene code, there are no references to ParametricFunction, so these changes would not, unfortunately, affect complex_function_scene. Seeing as Grant put ComplexFunctionScene in once_useful_constructs and has not been updated or tinkered with in a while, I suspect it might be deprecated.

**Comment by giladsofer** [comment]
I tried running your TestTrigDiscont example but it didn't work (it didn't fix the noise due to discontinuity). Is there something else you did other than using this code? Generally, I don't really understand how exactly I should use tol_point.

**Comment by TonyCrane** [comment]
Seems outdated, so closed this.

**Pull request closed without merging**
