### PR TITLE
Added SVG elliptical arc command support

### PR DESCRIPTION
**Pull request by chmunozpardo**
Added support for SVG arcs command. This is done by approximating the elliptical arc command through bezier curves.
So far can only accept an absolute and not relative command.

SVG support is important, especially for people that works with software like Inkscape or Illustrator, so I decided to make the effort to include this by using an existing library made in npm.

I attached a simple scene of a flag made with this.

https://user-images.githubusercontent.com/5047248/103669578-48f99f80-4f57-11eb-9096-cdc124ae88a9.mp4

### CODE REVIEW

**Comment by chmunozpardo** [comment]
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
	"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" width="600" height="600" viewBox="0 0 600 600">
	<desc>Flag of Germany</desc>
	<path d="M17.157, 200 A300,300 0 0,1 582.842, 200 z"
		fill="000000"/>
	<path d="M17.157, 200
			A300,300 0 0,0 17.157, 400
			H582.842
			A300,300 0 0,0 582.842, 200
			Z"
		fill="#DD0000" />
	<path d="M17.157, 400 A300,300 0 0,0 582.842, 400 z"
		fill="#FFCE00"/>
</svg>

```

This is the SVG of the flag used.

**Comment by naveen521kk** [comment]
@chmunozpardo Can you also send this PR to [ManimCommunity](https://github.com/manimcommunity/manim)?

**Comment by 3b1b** [comment]
This looks really helpful, thanks for doing it.

It looks like VMobjectFromSVGPathstring has been refactored a little bit since this change was made.  Would it be too much trouble to ask that you update it for the current version?  The best way to do this would be to add a method VMobject.add_elliptical_arc based on your code, then to edit the relevant term in the dict returned by VMobjectFromSVGPathstring.get_command_to_function_map

**Comment by chmunozpardo** [comment]
@3b1b No problem at all, actually I'm considering pushing other changes that I have done with the support on SVG as I showed [https://github.com/3b1b/manim/discussions/1319#discussion-1980986](url). Would you mind taking a look? I can attach the svg files that I used for the video in the link.

**Comment by 3b1b** [comment]
Thanks, @chmunozpardo, adding styling support for SVGs would be abundantly welcome!  I'd be more than happy to take a look.

**Comment by 3b1b** [comment]
Handled in https://github.com/3b1b/manim/pull/1598

**Pull request closed without merging**
