### PR TITLE
Move get_length() into TipableVMobject

### PR DESCRIPTION
**Pull request by jeanimal**
This reverts the commit "Cleaned Up Arrow Implementation (d489b5df5c77...), which introduced a bug in the CurvedArrow constructor (https://github.com/3b1b/manim/issues/446).  I had to fix one conflict in the imports, making sure to import both libraries rather than only one.

**Please ensure that your pull request works with the latest version of manim.**

Done with
git merge upstream/master

1. The motivation for making this change (or link the relevant issues)

https://github.com/3b1b/manim/issues/446

Since I did not see an obvious fix and no one had addressed the bug in several days, I created a rollback now rather than risk more conflicts as other commits are made on top of the bug.

2. How you tested the new behavior (e.g. a minimal working example, before/after
screenshots, gifs, commands, etc.) This is rather informal at the moment, but
the goal is to show us how you know the pull request works as intended.

I used https://github.com/zimmermant/manim_tutorial/blob/master/manim_tutorial_P37.py

BEFORE (at head):
python3 -m manim manim_tutorial_P37.py MoreShapes -pl
<snip>
AttributeError: 'CurvedArrow' object has no attribute 'get_length'

AFTER (after revert):
python3 -m manim manim_tutorial_P37.py MoreShapes -pl
<animation is generated>

### CODE REVIEW

**Comment by eulertour** [comment]
I don't have the time to check this PR now, but as a heads-up the tests currently don't matter at all.

**Comment by jeanimal** [comment]
Do you have time to check this pull request?  It's a very straightforward change generated by
git revert d489b5df5c77a597a71c4fd89597e3d48d5b4d9a
And then merging a line in imports so that both imports still happened.

By "test" I think you mean the travis build, which has been broken for a while: https://travis-ci.org/3b1b/manim/builds

I just synced to head because I saw there were a few more commits and confirmed this still works:
python3 -m manim manim_tutorial_P37.py MoreShapes -pl

That's my version of "tests."

**Comment by eulertour** [comment]
Sorry for being so slow on this. It's unsafe to revert a commit without knowing its motivation, as it likely causes some desired behavior in addition to the bug. It'd be safest to find a way to fix the bug without reverting the entire commit.

**Comment by jeanimal** [comment]
Thanks for taking a look.

We got lucky-- while typing up how I had tried and failed to fix the bug, I saw a simple fix-- moving the get_length() method to the base class.  Please take a look.

I tested it with the tutorial I mentioned before, which generates several shapes, and they all seemed fine:
python3 -m manim manim_tutorial_P37.py Shapes -pl
python3 -m manim manim_tutorial_P37.py MoreShapes -pl

P.S. I don't actually use CurvedArrow in anything I do, so if this request doesn't work out, I'm done.

**Comment by eulertour** [comment]
This looks good. Thanks!

**Comment by jeanimal** [comment]
Thanks for updating the title after the changes.  I deleted the branch but will keep my fork for future bug fixes.

**Pull request merged**
