### PR TITLE
latex can't recognize path seperator \\ in windows

### PR DESCRIPTION
**Pull request by zombie110year**
Modify path as posix style before transport it to system command to fix issue #505 

I ran the example_scenes.py and pass all cases.

### CODE REVIEW

**Comment by sajidnisar** [comment]
Thanks @zombie110year; a must change for manim to work on Windows (10) with latex!

**Comment by 435vic** [comment]
Definitely an issue that should be looked into.

**Comment by markchalmersUC** [comment]
Just wanted to say thank you! this is the only thing that fixed my latex issue on windows 10.

**Comment by TooYoungTooSimp** [comment]
A better fix than my local `.replace('\\','/')` !
It's a must merge fix for manim indeed.

**Comment by filipppp** [comment]
Can we please merge this?

**Pull request merged**
