### PR TITLE
Update complex_transformation_scene.py #498

### PR DESCRIPTION
**Pull request by yinjann**
Fixing problems with the animation of the zeta transformation

Thanks for contributing to manim!

**Please ensure that your pull request works with the latest version of manim.**
You should also include:

1. The motivation for making this change (or link the relevant issues)
2. How you tested the new behavior (e.g. a minimal working example, before/after
screenshots, gifs, commands, etc.) This is rather informal at the moment, but
the goal is to show us how you know the pull request works as intended.

### CODE REVIEW

**Comment by giladsofer** [comment]
Sorry if this is basic, but how do you install these updates? (this and also update coordinate system)

**Comment by yinjann** [comment]
You don't have to apologize. click on my pull request "Update complex_transformation_scene.py" there you will see the changes you have to make. Basically it's going to the file manim / manimlib / once_useful_constructs / complex_transformation_scene.py
there you have to delete the lines 128,129,131,132
This was the cause of the animation acting strangely. I suppose it was because they later updated other parts of the code and those lines were left over

**Comment by giladsofer** [comment]
I deleted the lines you suggested and although the animation is a bit better, there is still a lot of noise due to the singularities of the function (I tried it with f(z)=1/z). Do you have an idea on how to solve this?

**Comment by yinjann** [comment]
yes, it seems that add_extra_plane_lines_for_zeta() doesn't work well.
Instead use: 

        prueba = self.get_dense_grid()
        self.plane.submobjects = [prueba]
        self.apply_zeta_function()

Check my changes #1169

**Comment by giladsofer** [comment]
But is this relevant for the function 1/z if I'm not using the zeta function? (I only use complex transformation scene)

**Review by lemsi19 — COMMENTED** [review]
1b82ea85074548f2ae1e8f9320bdba0a52760c49!

**Pull request closed without merging**
