### PR TITLE
Update installation.rst added FFmpeg install

### PR DESCRIPTION
**Pull request by rudransh61**
Hi Team Manim

# Added ffmpeg install in docs

Hi, I am Rudransh Bharwdaj a developer. When I was making some project I face many problem while installing ffmpeg and I realized that many other developers are also facing this issue so I added how to install ffmpeg for windows, macos, and linux.
If there is any correction please tell me i will solve it .
Thank you

Excited for SoME3

### CODE REVIEW

**Comment by rudransh61** [comment]
Try to solve this as fast as possible because people are making videos for SoME3 using manim and we have to insure that they will not face any issue and documentation will complete and maintained .
Thanks (again for reading this)

**Comment by rudransh61** [comment]
Please reply

**Comment by rudransh61** [comment]
.....

**Comment by rudransh61** [comment]
broooo pls rply??

**Comment by rudransh61** [comment]
thats baad

**Review by furkandrms — APPROVED** [review]

**Comment by rudransh61** [comment]
pls tell is there is any issue or it is ready to merge??

**Comment by rudransh61** [comment]
@3b1b is there is any issue related to this request pls reply sir ??

**Review by rudransh61 — COMMENTED** [review]
noice boi (reviewing myself **)

**Comment by rudransh61** [comment]
@3b1b @charliepark @shalunov pls review and merge it

**Pull request merged**
