### PR TITLE
Fix some bugs of the shaders branch

### PR DESCRIPTION
**Pull request by Tony031218**
Here are some bug fixes for the shaders branch.

- The first commit https://github.com/3b1b/manim/commit/79b81363309d4b9eb1a125d6dac75ee5cd674bc1 : I'm trying to make the `Text` class work perfectly in shaders. But I found that if I remove some of the changes in #1030(or #1031), the `Text` will directly work fine. So I revert them.
- The second commit https://github.com/3b1b/manim/commit/78848b971cd3f7db0831db58ad4e9c40d1cf61e4 : I checked the docs of `logging` in the official python documentation and also checked the source code. I found that `logging.log` cannot receive the `file` argument, so I deleted this line, otherwise the following error will appear:
```python
  File ".../manimlib/extract_scene.py", line 82, in get_scenes_to_render
    file=sys.stderr
  File ".../Anaconda3/envs/manim/lib/logging/__init__.py", line 2014, in log
    root.log(level, msg, *args, **kwargs)
  File ".../Anaconda3/envs/manim/lib/logging/__init__.py", line 1449, in log
    self._log(level, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'file'
```
- The fourth commit https://github.com/3b1b/manim/commit/f696ba4100d43e67a3ebd05c05b514086cf435b6 : I write a brief example for `Text` to introduce and test it.
- The fifth commit https://github.com/3b1b/manim/pull/1315/commits/fa3cad18e0e4d55e727b09ff210a79befa612b19 : Added the missing `ipython` package mentioned in https://github.com/3b1b/manim/pull/1301#issuecomment-753643071, and updated the `environment.yml` for Anaconda.
- The sixth commit https://github.com/3b1b/manim/pull/1315/commits/c6fcaa93bb9c4482815fd03b19de2a52951cf143 : Deleted the file `stream_starter.py`. Because it seems that stream related functions have been completely deleted, but this file remains.
- The eighth commit https://github.com/3b1b/manim/pull/1315/commits/7c04edcced38eea1046b934aa853e8500c4b3af9 : Added `font_size` to `Text`, and synchronized to the same size effect as `TextMobject` :
VG))B17{8$14CRJGRMDD7`R

---
@3b1b please have a look at these changes.
By the way, there is also a bug that I can't fix it, I talked in detail in #1314

### CODE REVIEW

**Comment by DVCosmos** [comment]
Hey @Tony031218 and @3b1b, I just wanted to point out a small bug in camera.py file.
In the class 'CameraFrame', the function 'set_gamma' ([Line 97](https://github.com/3b1b/manim/blob/shaders/manimlib/camera/camera.py#L97)) is returning self.set_rotation(phi=phi) instead of self.set_rotation(gamma=gamma).

Please consider to change this.

**Comment by 3b1b** [comment]
Looks good, thanks!

**Comment by 3b1b** [comment]
It seems that there's some kind of issue with Text.find_indexes which keeps set_color_by_t2c from working.  It looks like this stems from assuming that the number of characters in self.text matches the number of submobjects, but with whitespace, this won't be true.  If you have a moment, is this something you can look at?

image

**Comment by Tony031218** [comment]
> It seems that there's some kind of issue with Text.find_indexes which keeps set_color_by_t2c from working. It looks like this stems from assuming that the number of characters in self.text matches the number of submobjects, but with whitespace, this won't be true. If you have a moment, is this something you can look at?
> 
> image


But this display properly on my computer: 
image
image
but I also found that the changes in #1035 are not synchronized to the shaders, which improves Text's handling of non-display characters such as whitespaces. I will open a new pull request later.

**Pull request merged**
